package net.kollnig.distractionlib;

import android.view.accessibility.AccessibilityNodeInfo;

import java.util.ArrayList;
import java.util.List;

/**
 * Generates filter rule strings from AccessibilityNodeInfo nodes.
 * Priority: viewId > path > text > className.
 * contentDescription is kept for backward compatibility but not generated by the picker.
 */
public class ElementPickerRuleGenerator {
    public static String generateRule(AccessibilityNodeInfo node, AccessibilityNodeInfo rootNode,
                                      String packageName, String comment) {
        StringBuilder rule = new StringBuilder(packageName);

        String viewId = node.getViewIdResourceName();
        CharSequence text = node.getText();
        CharSequence className = node.getClassName();

        if (viewId != null && !viewId.isEmpty()) {
            rule.append("##viewId=").append(viewId);
        } else {
            String path = generatePath(node, rootNode);
            if (path != null) {
                rule.append("##path=").append(path);
            } else if (text != null && text.length() > 0) {
                rule.append("##text=").append(text);
            } else if (className != null && className.length() > 0) {
                rule.append("##className=").append(className);
            }
        }

        if (comment != null && !comment.isEmpty()) {
            rule.append("##comment=").append(comment);
        }

        return rule.toString();
    }

    public static String generatePath(AccessibilityNodeInfo target, AccessibilityNodeInfo rootNode) {
        if (target == null || rootNode == null) return null;

        List<AccessibilityNodeInfo> ancestors = new ArrayList<>();
        List<Integer> indices = new ArrayList<>();

        AccessibilityNodeInfo current = AccessibilityNodeInfo.obtain(target);
        while (current != null) {
            if (nodeEquals(current, rootNode)) {
                current.recycle();
                break;
            }

            AccessibilityNodeInfo parent = current.getParent();
            if (parent == null) {
                current.recycle();
                break;
            }

            int indexAmongSameClass = 0;
            CharSequence currentClass = current.getClassName();
            if (currentClass != null) {
                for (int i = 0; i < parent.getChildCount(); i++) {
                    AccessibilityNodeInfo sibling = parent.getChild(i);
                    if (sibling == null) continue;
                    if (nodeEquals(sibling, current)) {
                        sibling.recycle();
                        break;
                    }
                    CharSequence siblingClass = sibling.getClassName();
                    if (siblingClass != null
                            && siblingClass.toString().equals(currentClass.toString())) {
                        indexAmongSameClass++;
                    }
                    sibling.recycle();
                }
            }

            ancestors.add(current);
            indices.add(indexAmongSameClass);
            current = parent;
        }

        if (ancestors.isEmpty()) return null;

        StringBuilder path = new StringBuilder();
        for (int i = ancestors.size() - 1; i >= 0; i--) {
            if (path.length() > 0) path.append(">");
            CharSequence cls = ancestors.get(i).getClassName();
            path.append(cls != null ? cls.toString() : "Unknown");
            path.append("[").append(indices.get(i)).append("]");
            ancestors.get(i).recycle();
        }

        return path.toString();
    }

    private static boolean nodeEquals(AccessibilityNodeInfo a, AccessibilityNodeInfo b) {
        if (a == null || b == null) return false;
        return a.equals(b);
    }

    public static String describeNode(AccessibilityNodeInfo node) {
        StringBuilder sb = new StringBuilder();

        CharSequence className = node.getClassName();
        if (className != null) {
            String fullName = className.toString();
            int lastDot = fullName.lastIndexOf('.');
            sb.append(lastDot >= 0 ? fullName.substring(lastDot + 1) : fullName);
        }

        String viewId = node.getViewIdResourceName();
        if (viewId != null && !viewId.isEmpty()) {
            int slashIndex = viewId.indexOf('/');
            String shortId = slashIndex >= 0 ? viewId.substring(slashIndex + 1) : viewId;
            sb.append(" #").append(shortId);
        }

        CharSequence desc = node.getContentDescription();
        if (desc != null && desc.length() > 0) {
            sb.append(" \"").append(truncate(desc.toString(), 30)).append("\"");
        }

        CharSequence text = node.getText();
        if (text != null && text.length() > 0) {
            sb.append(" [").append(truncate(text.toString(), 30)).append("]");
        }

        return sb.toString().trim();
    }

    public static String getSelectorDescription(AccessibilityNodeInfo node,
                                                AccessibilityNodeInfo rootNode) {
        String viewId = node.getViewIdResourceName();
        if (viewId != null && !viewId.isEmpty()) {
            return "View ID: " + viewId;
        }

        String path = generatePath(node, rootNode);
        if (path != null) {
            return "Path: " + truncate(path, 60);
        }

        CharSequence text = node.getText();
        if (text != null && text.length() > 0) {
            return "Text: " + truncate(text.toString(), 50);
        }

        CharSequence className = node.getClassName();
        if (className != null) {
            return "Class: " + className;
        }

        return "Unknown element";
    }

    public static String generateRuleForAll(AccessibilityNodeInfo node, AccessibilityNodeInfo rootNode,
                                            String packageName, String comment) {
        StringBuilder rule = new StringBuilder(packageName);
        String wildcardPath = generatePathWithWildcard(node, rootNode);

        if (wildcardPath != null) {
            rule.append("##path=").append(wildcardPath);
        } else {
            CharSequence className = node.getClassName();
            if (className != null && className.length() > 0) {
                rule.append("##className=").append(className);
            } else {
                String viewId = node.getViewIdResourceName();
                if (viewId != null && !viewId.isEmpty()) {
                    rule.append("##viewId=").append(viewId);
                }
            }
        }

        if (comment != null && !comment.isEmpty()) {
            rule.append("##comment=").append(comment);
        }

        return rule.toString();
    }

    public static String generatePathWithWildcard(AccessibilityNodeInfo target,
                                                  AccessibilityNodeInfo rootNode) {
        if (target == null || rootNode == null) return null;

        List<AccessibilityNodeInfo> ancestors = new ArrayList<>();
        List<Integer> indices = new ArrayList<>();

        AccessibilityNodeInfo current = AccessibilityNodeInfo.obtain(target);
        while (current != null) {
            if (nodeEquals(current, rootNode)) {
                current.recycle();
                break;
            }

            AccessibilityNodeInfo parent = current.getParent();
            if (parent == null) {
                current.recycle();
                break;
            }

            int indexAmongSameClass = 0;
            CharSequence currentClass = current.getClassName();
            if (currentClass != null) {
                for (int i = 0; i < parent.getChildCount(); i++) {
                    AccessibilityNodeInfo sibling = parent.getChild(i);
                    if (sibling == null) continue;
                    if (nodeEquals(sibling, current)) {
                        sibling.recycle();
                        break;
                    }
                    CharSequence siblingClass = sibling.getClassName();
                    if (siblingClass != null
                            && siblingClass.toString().equals(currentClass.toString())) {
                        indexAmongSameClass++;
                    }
                    sibling.recycle();
                }
            }

            ancestors.add(current);
            indices.add(indexAmongSameClass);
            current = parent;
        }

        if (ancestors.isEmpty()) return null;

        StringBuilder path = new StringBuilder();
        for (int i = ancestors.size() - 1; i >= 0; i--) {
            if (path.length() > 0) path.append(">");
            CharSequence cls = ancestors.get(i).getClassName();
            path.append(cls != null ? cls.toString() : "Unknown");
            if (i == 0) {
                path.append("[*]");
            } else {
                path.append("[").append(indices.get(i)).append("]");
            }
            ancestors.get(i).recycle();
        }

        return path.toString();
    }

    private static String truncate(String s, int max) {
        if (s.length() <= max) return s;
        return s.substring(0, max - 1) + "...";
    }
}
