package net.kollnig.distractionlib;

import android.graphics.Rect;
import android.view.accessibility.AccessibilityNodeInfo;

import java.util.ArrayList;
import java.util.List;

/**
 * Generates filter rule strings from AccessibilityNodeInfo nodes.
 * Priority: viewId > anchored path > path > text > className.
 * contentDescription is kept for backward compatibility but not generated by the picker.
 */
public class ElementPickerRuleGenerator {

    /**
     * A view hierarchy path, measured from the nearest ancestor carrying a view ID when there
     * is one, and from the window root otherwise.
     */
    public static class NodePath {
        public final String anchorViewId;
        public final String path;

        NodePath(String anchorViewId, String path) {
            this.anchorViewId = anchorViewId;
            this.path = path;
        }
    }

    public static String generateRule(AccessibilityNodeInfo node, AccessibilityNodeInfo rootNode,
                                      String packageName, String comment) {
        StringBuilder rule = new StringBuilder(packageName);

        String viewId = node.getViewIdResourceName();
        CharSequence text = node.getText();
        CharSequence className = node.getClassName();

        if (viewId != null && !viewId.isEmpty()) {
            rule.append("##viewId=").append(viewId);
        } else {
            NodePath anchored = generateAnchoredPath(node, rootNode);
            if (anchored != null && anchored.anchorViewId != null) {
                rule.append("##viewId=").append(anchored.anchorViewId)
                        .append("##childPath=").append(anchored.path);
            } else if (anchored != null) {
                rule.append("##path=").append(anchored.path);
            } else if (text != null && text.length() > 0) {
                rule.append("##text=").append(sanitizeRuleValue(text.toString()));
            } else if (className != null && className.length() > 0) {
                rule.append("##className=").append(className);
            }
        }

        if (comment != null && !comment.isEmpty()) {
            rule.append("##comment=").append(sanitizeRuleValue(comment));
        }

        return rule.toString();
    }

    /** A selector strong enough to click, together with the wording shown to the user. */
    public static class NavigationSelector {
        /** Rule fragment, including its leading {@code ##}. */
        public final String ruleFragment;
        public final String description;

        NavigationSelector(String ruleFragment, String description) {
            this.ruleFragment = ruleFragment;
            this.description = description;
        }
    }

    /**
     * Picks a selector for an element that will be <em>clicked</em> rather than covered, or
     * returns null if none of the available ones is good enough.
     *
     * <p>The ordering differs from {@link #generateRule} because the failure modes differ. A
     * blocking rule that matches the wrong element covers the wrong box; a navigation rule that
     * matches the wrong element taps it. So the weak rungs {@link #generateRule} falls back on
     * are refused outright here:
     *
     * <ul>
     *   <li>{@code className} would match the first FrameLayout on screen.
     *   <li>A root-relative {@code path} re-resolves against whatever occupies that position
     *       after a layout change, which for a tab bar means tapping a different tab.
     *   <li>{@code text} is not consulted by the navigation matcher at all.
     * </ul>
     *
     * <p>A content description outranks an anchored path here, the reverse of the usual
     * preference for structure over labels. A description that stops matching produces no click;
     * a path whose index has shifted produces the wrong one, and silence is the better failure.
     * Returning null is likewise better than a rule that will one day tap something unintended.
     */
    public static NavigationSelector navigationSelector(AccessibilityNodeInfo node,
                                                        AccessibilityNodeInfo rootNode) {
        if (node == null) return null;

        String viewId = node.getViewIdResourceName();
        if (viewId != null && !viewId.isEmpty()) {
            return new NavigationSelector("##viewId=" + viewId, "View ID: " + viewId);
        }

        CharSequence desc = node.getContentDescription();
        if (desc != null && desc.length() > 0) {
            String value = sanitizeRuleValue(desc.toString()).trim();
            // A pipe separates alternatives in a desc list, so one inside a description would
            // parse into two that each match nothing. Fall through rather than emit that.
            if (!value.isEmpty() && !value.contains("|")) {
                return describedSelector(value);
            }
        }

        NodePath anchored = generateAnchoredPath(node, rootNode);
        if (anchored != null && anchored.anchorViewId != null) {
            return new NavigationSelector(
                    "##viewId=" + anchored.anchorViewId + "##childPath=" + anchored.path,
                    "Path under " + anchored.anchorViewId + ": " + truncate(anchored.path, 40));
        }

        return null;
    }

    /**
     * Turns a content description into a selector, dropping any trailing status.
     *
     * <p>A description is written to be read aloud, so it carries what is true right now:
     * "Unread filter, 25, unselected", "someone's story, 3 of 27, Unseen.". Stored whole, the
     * rule dies the moment that count changes. The convention that status is appended after a
     * comma comes from how the platform concatenates a label with its state, not from any one
     * app, so cutting there generalises.
     *
     * <p>The cut is a suggestion, not a hidden matching rule: what is stored is a plain prefix,
     * the whole of it is shown in the confirmation card, and the caller checks it still picks
     * out exactly one element before offering to save it.
     */
    static NavigationSelector describedSelector(String value) {
        int comma = value.indexOf(',');
        if (comma <= 0) {
            return new NavigationSelector("##desc=" + value, "Description: " + value);
        }
        String label = value.substring(0, comma).trim();
        if (label.isEmpty()) {
            return new NavigationSelector("##desc=" + value, "Description: " + value);
        }
        return new NavigationSelector("##desc=" + label + "##descMatch=prefix",
                "Description starting with: " + label);
    }

    /**
     * Counts the visible nodes a description-based rule would match.
     *
     * <p>A looser comparison is only safe if it still names one thing. Checking against the
     * screen the element was picked from turns "refuse rather than guess" from a ranking
     * preference into something actually tested. It cannot speak for screens not on display.
     */
    public static int countDescriptionMatches(AccessibilityNodeInfo node, FilterRule rule) {
        if (node == null) return 0;

        int count = node.isVisibleToUser() && rule.matchesDescription(node.getContentDescription())
                ? 1 : 0;
        for (int i = 0; i < node.getChildCount(); i++) {
            AccessibilityNodeInfo child = node.getChild(i);
            if (child == null) continue;
            try {
                count += countDescriptionMatches(child, rule);
            } finally {
                child.recycle();
            }
        }
        return count;
    }

    /**
     * Builds a navigation rule for an element, or returns null when
     * {@link #navigationSelector} finds nothing worth clicking.
     */
    public static String generateNavigationRule(AccessibilityNodeInfo node,
                                                AccessibilityNodeInfo rootNode,
                                                String packageName, String comment) {
        NavigationSelector selector = navigationSelector(node, rootNode);
        if (selector == null) {
            return null;
        }

        StringBuilder rule = new StringBuilder(packageName).append(selector.ruleFragment);
        if (comment != null && !comment.isEmpty()) {
            rule.append("##comment=").append(sanitizeRuleValue(comment));
        }
        return rule.toString();
    }

    public static String generatePath(AccessibilityNodeInfo target, AccessibilityNodeInfo rootNode) {
        NodePath result = walkUp(target, rootNode, false, false);
        return result != null ? result.path : null;
    }

    /**
     * Builds a path measured from the nearest ancestor that carries a view ID. Such a path
     * only depends on the few levels below a stable anchor, so it survives the layout changes
     * above it that break a path measured from the window root.
     */
    public static NodePath generateAnchoredPath(AccessibilityNodeInfo target,
                                                AccessibilityNodeInfo rootNode) {
        return walkUp(target, rootNode, true, false);
    }

    private static NodePath walkUp(AccessibilityNodeInfo target, AccessibilityNodeInfo rootNode,
                                   boolean stopAtViewIdAncestor, boolean wildcardLeaf) {
        if (target == null || rootNode == null) return null;

        // Segments are collected leaf first and reversed at the end.
        List<String> segments = new ArrayList<>();
        String anchorViewId = null;

        AccessibilityNodeInfo current = AccessibilityNodeInfo.obtain(target);
        while (current != null) {
            if (nodeEquals(current, rootNode)) {
                current.recycle();
                break;
            }

            AccessibilityNodeInfo parent = current.getParent();
            if (parent == null) {
                current.recycle();
                break;
            }

            CharSequence currentClass = current.getClassName();
            String index = wildcardLeaf && segments.isEmpty()
                    ? "*"
                    : String.valueOf(indexAmongSameClass(parent, current));
            segments.add((currentClass != null ? currentClass.toString() : "Unknown")
                    + "[" + index + "]");
            current.recycle();

            String parentViewId = parent.getViewIdResourceName();
            if (stopAtViewIdAncestor && parentViewId != null && !parentViewId.isEmpty()) {
                anchorViewId = parentViewId;
                parent.recycle();
                break;
            }

            current = parent;
        }

        if (segments.isEmpty()) return null;

        StringBuilder path = new StringBuilder();
        for (int i = segments.size() - 1; i >= 0; i--) {
            if (path.length() > 0) path.append(">");
            path.append(segments.get(i));
        }

        return new NodePath(anchorViewId, path.toString());
    }

    private static int indexAmongSameClass(AccessibilityNodeInfo parent,
                                           AccessibilityNodeInfo child) {
        CharSequence childClass = child.getClassName();
        if (childClass == null) return 0;

        int index = 0;
        for (int i = 0; i < parent.getChildCount(); i++) {
            AccessibilityNodeInfo sibling = parent.getChild(i);
            if (sibling == null) continue;
            if (nodeEquals(sibling, child)) {
                sibling.recycle();
                break;
            }
            CharSequence siblingClass = sibling.getClassName();
            if (siblingClass != null && siblingClass.toString().equals(childClass.toString())) {
                index++;
            }
            sibling.recycle();
        }
        return index;
    }

    private static boolean nodeEquals(AccessibilityNodeInfo a, AccessibilityNodeInfo b) {
        if (a == null || b == null) return false;
        return a.equals(b);
    }

    public static String describeNode(AccessibilityNodeInfo node) {
        StringBuilder sb = new StringBuilder();

        CharSequence className = node.getClassName();
        if (className != null) {
            String fullName = className.toString();
            int lastDot = fullName.lastIndexOf('.');
            sb.append(lastDot >= 0 ? fullName.substring(lastDot + 1) : fullName);
        }

        String viewId = node.getViewIdResourceName();
        if (viewId != null && !viewId.isEmpty()) {
            int slashIndex = viewId.indexOf('/');
            String shortId = slashIndex >= 0 ? viewId.substring(slashIndex + 1) : viewId;
            sb.append(" #").append(shortId);
        }

        CharSequence desc = node.getContentDescription();
        if (desc != null && desc.length() > 0) {
            sb.append(" \"").append(truncate(desc.toString(), 30)).append("\"");
        }

        CharSequence text = node.getText();
        if (text != null && text.length() > 0) {
            sb.append(" [").append(truncate(text.toString(), 30)).append("]");
        }

        return sb.toString().trim();
    }

    /** A short label that explains the selected thing without requiring Android vocabulary. */
    public static String plainLanguageDescription(AccessibilityNodeInfo node) {
        if (node == null) return "element";
        CharSequence label = node.getContentDescription();
        if (label == null || label.length() == 0) label = node.getText();
        if (label != null && label.length() > 0) return label.toString();
        CharSequence className = node.getClassName();
        String name = className == null ? "" : className.toString();
        if (name.endsWith("ImageView")) return "picture";
        if (name.endsWith("Button")) return "button";
        if (name.endsWith("RecyclerView") || name.endsWith("ListView")) return "list";
        return "element";
    }

    /** Counts visible siblings selected by the wildcard leaf used by generateRuleForAll. */
    public static int countGeneralizedSiblingMatches(AccessibilityNodeInfo node) {
        if (node == null) return 0;
        AccessibilityNodeInfo parent = node.getParent();
        if (parent == null) return node.isVisibleToUser() ? 1 : 0;
        try {
            CharSequence selectedClass = node.getClassName();
            int count = 0;
            for (int i = 0; i < parent.getChildCount(); i++) {
                AccessibilityNodeInfo sibling = parent.getChild(i);
                if (sibling == null) continue;
                try {
                    CharSequence siblingClass = sibling.getClassName();
                    if (sibling.isVisibleToUser() && selectedClass != null
                            && siblingClass != null
                            && selectedClass.toString().contentEquals(siblingClass)) count++;
                } finally {
                    sibling.recycle();
                }
            }
            return count;
        } finally {
            parent.recycle();
        }
    }

    /** Refuses only a selection that is itself the active window's content surface. */
    public static boolean refusesFullScreenSelection(AccessibilityNodeInfo node,
                                                     AccessibilityNodeInfo rootNode) {
        if (node == null || rootNode == null) return false;
        if (node.equals(rootNode)) return true;

        Rect nodeBounds = new Rect();
        Rect rootBounds = new Rect();
        node.getBoundsInScreen(nodeBounds);
        rootNode.getBoundsInScreen(rootBounds);
        return !nodeBounds.isEmpty() && !rootBounds.isEmpty()
                && nodeBounds.contains(rootBounds);
    }

    public static String getSelectorDescription(AccessibilityNodeInfo node,
                                                AccessibilityNodeInfo rootNode) {
        String viewId = node.getViewIdResourceName();
        if (viewId != null && !viewId.isEmpty()) {
            return "View ID: " + viewId;
        }

        NodePath anchored = generateAnchoredPath(node, rootNode);
        if (anchored != null && anchored.anchorViewId != null) {
            return "Path under " + anchored.anchorViewId + ": " + truncate(anchored.path, 40);
        }
        if (anchored != null) {
            return "Path: " + truncate(anchored.path, 60);
        }

        CharSequence text = node.getText();
        if (text != null && text.length() > 0) {
            return "Text: " + truncate(text.toString(), 50);
        }

        CharSequence className = node.getClassName();
        if (className != null) {
            return "Class: " + className;
        }

        return "Unknown element";
    }

    public static String generateRuleForAll(AccessibilityNodeInfo node, AccessibilityNodeInfo rootNode,
                                            String packageName, String comment) {
        StringBuilder rule = new StringBuilder(packageName);
        NodePath anchored = walkUp(node, rootNode, true, true);

        if (anchored != null && anchored.anchorViewId != null) {
            rule.append("##viewId=").append(anchored.anchorViewId)
                    .append("##childPath=").append(anchored.path);
        } else if (anchored != null) {
            rule.append("##path=").append(anchored.path);
        } else {
            CharSequence className = node.getClassName();
            if (className != null && className.length() > 0) {
                rule.append("##className=").append(className);
            } else {
                String viewId = node.getViewIdResourceName();
                if (viewId != null && !viewId.isEmpty()) {
                    rule.append("##viewId=").append(viewId);
                }
            }
        }

        if (comment != null && !comment.isEmpty()) {
            rule.append("##comment=").append(sanitizeRuleValue(comment));
        }

        return rule.toString();
    }

    public static String generatePathWithWildcard(AccessibilityNodeInfo target,
                                                  AccessibilityNodeInfo rootNode) {
        NodePath result = walkUp(target, rootNode, false, true);
        return result != null ? result.path : null;
    }

    /**
     * Removes the ## separator to prevent rule injection.
     */
    static String sanitizeRuleValue(String value) {
        if (value == null) return null;
        return value.replace("##", "");
    }

    private static String truncate(String s, int max) {
        if (s.length() <= max) return s;
        return s.substring(0, max - 1) + "...";
    }
}
